---
version: 2.1

orbs:
  executor-tools: twdps/executor-tools@1.3.0
  op: twdps/onepassword@1.0.0

# ================================================================= global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: op run --env-file op.env -- /bin/bash -eo pipefail
  registry:
    description: publish to this registry
    type: string
    default: docker.io

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

# ================================================================= workflows

workflows:
  version: 2
  circleci-python-builder-pipeline:
    jobs:
      - executor-tools/machine-executor-dev-release:
          name: dev-build
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          image: twdps/circleci-python-builder
          tag: edge
          docker-cve-scan: true
          snyk-organization: twdps
          severity-threshold: low
          cis-docker-image-scan: true
          skip-base-image: true
          bats-test: true
          test-path: test/circleci_python_builder.bats
          container-name: circleci-python-builder-edge
          after-checkout:
            - op/env:
                env-file: op.env
          before-build:
            - run:
                name: update CREATED and VERSION in LABELS
                command: |
                  sed -i "s/CREATED/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/g" Dockerfile
                  sed -i "s/VERSION/${CIRCLE_SHA1}/g" Dockerfile
          filters: *on-push-main

      - executor-tools/publish:
          name: release
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          pull-tag: edge
          image: twdps/circleci-python-builder
          release-tag: stable
          sign-image: true
          sbom: true
          after-publish:
            - run:
                name: setup cosign keys
                command: |
                  op inject -i cosign.key.env -o cosign.key
                  op inject -i cosign.pub.env -o cosign.pub
          filters: *on-tag-main

  generate-release-notes:
    jobs:
      - executor-tools/release:
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          on-tag: true
          filters: *on-tag-main

  # builds monthly to confirm base image version health
  circleci-python-builder-recurring-build:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - executor-tools/dev-release:
          name: nightly-build
          shell: << pipeline.parameters.shell-options >>
          context: << pipeline.parameters.context >>
          registry: << pipeline.parameters.registry >>
          image: twdps/circleci-python-builder
          tag: nightly
          cis-docker-image-scan: true
          docker-cve-scan: true
          severity-threshold: low
          snyk-organization: twdps
          bats-test: true
          test-path: test/circleci_python_builder.bats
          entry-point: /bin/ash
          container-name: circleci-python-builder-nightly
          after-checkout:
            - op/env:
                env-file: op.env
          before-build:
            - run:
                name: update CREATED and VERSION in LABELS
                command: |
                  sed -i "s/CREATED/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/g" Dockerfile
                  sed -i "s/VERSION/${CIRCLE_SHA1}/g" Dockerfile
